### ISSUE TITLE
unable to create Squid Asset due to squid-java failure

### ISSUE THREAD

**Issue by tmarble** [DEX-Company/starfish-java#84]
Another failed integration test (as in #81) allows an error in
**squid-java**  `src/test/java/com/oceanprotocol/squid/api/AssetsApiIT.java`
to go unnoticed.

An attempt to reprise the intended use of the API (as shown in PR #83) fails with the same error:
```
=== eCreateAsset ===
19:12:28.346 [main] ERROR com.oceanprotocol.squid.manager.OceanManager - Unable to retrieve DDO No events found for did:op:8d88b56dfaac44f4a2061189ce5697c4fa155b3af3be44adb814b52c83179146
com.oceanprotocol.squid.exceptions.DDOException: Unable to retrieve DDO No events found for did:op:8d88b56dfaac44f4a2061189ce5697c4fa155b3af3be44adb814b52c83179146
	at com.oceanprotocol.squid.manager.OceanManager.resolveDID(OceanManager.java:126)
	at com.oceanprotocol.squid.api.impl.AssetsImpl.resolve(AssetsImpl.java:54)
	at sg.dex.squid.SquidIntegrationTests.eCreateAsset(SquidIntegrationTests.java:177)

```

**Comment by mikera** [comment]
Worth filing an issue with Squid Java? I assume the asset has already been created and confirmed on chain?
